using System;
using RimWorld;
using Verse;
using Verse.AI;

namespace MindJackUniqueWeaponBind
{
    public class MJUBW_RegisterToWeapon : FloatMenuOptionProvider
    {
        protected override bool Drafted => true;
        protected override bool Undrafted => true;
        protected override bool Multiselect => false;

        //Adding the context menu item to allow Binding
        protected override FloatMenuOption GetSingleOptionFor(Thing clickedThing, FloatMenuContext context)
        {
            Pawn currentPawn = context.FirstSelectedPawn;
            //This checks if the selected weapon has a Port
            if (clickedThing.HasComp<MJUWB_PortThingComp>())
                {
                //Sets the port so we can modify it later
                MJUWB_PortThingComp port = clickedThing.TryGetComp<MJUWB_PortThingComp>();
                //Adds context menu "Bind to (Weapon Name)"
                //TOADD: Context menues for: PAWN W/O Mind Jack, PAWN W/ Registered Mind Jack
                return FloatMenuUtility.DecoratePrioritizedTask(new FloatMenuOption("MJUWB_Bind".Translate(clickedThing.Label), () =>
                {
                    //Calls bond process and sets quality to Good if the weapon is of a higher quality (to account for mods)
                    port.ConnectToPort(currentPawn);
                    CompQuality wepQuality = clickedThing.TryGetComp<CompQuality>();

                    if (wepQuality.Quality > QualityCategory.Good)
                    {
                        //All unique weapons generated by the game have Art by default, so CompArt will already be set
                        //This method should not add Art to a weapon that was modded to attach a unique trait and has no Art already.
                        wepQuality.SetQuality(QualityCategory.Good, null);
                    }
                    //JUST FOR TESTING REMOVE LATER
                    Log.Message("Bind Clicked");
                    Log.Message(port.registeredPawn.NameFullColored);
                }), context.FirstSelectedPawn, clickedThing);
            }
            return null;
        }
    }
}
       