using MindJackUniqueWeaponBind;
using RimWorld;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Verse;
using Verse.AI;
using Verse.Sound;
using static UnityEngine.GridBrushBase;

namespace MindJackMod
{
    //This is the Job that takes place whenever a Pawn tries to register a weapon
    public class MJUWE_RegisterJob : JobDriver
    {
        public int finish = 1080;
        public const int tickProgression = GenTicks.TicksPerRealSecond;
        public int currentTick = 0;
        public float Progression => currentTick / finish;


        public override bool TryMakePreToilReservations(bool errorOnFailed)
        {
            return pawn.Reserve(TargetThingA, job, 1, -1, null, errorOnFailed);
        }

        //This Toil tells to pawn to go to the item "register" to ir for a few seconds, then calls in the methods used for the actual registration of the port to the weapon
        //Toils are just a list of instructions, and when the toil is yield return'ed, it adds it to the list of instructions to do. When a job starts it does all the Toils
        protected override IEnumerable<Toil> MakeNewToils()
        {

            //This fails the job if the weapon for some reason stops existing
            this.FailOnDespawnedNullOrForbidden(TargetIndex.A);

            //This tells the pawn to go to the weapon
            yield return Toils_Goto.GotoThing(TargetIndex.A, PathEndMode.Touch);
            
            //This tells the pawn to wait and play a little hacking animation in the meantime
            yield return Toils_General.WaitWith(TargetIndex.A, finish)
                .FailOnDestroyedNullOrForbidden(TargetIndex.A)
                .FailOnCannotTouch(TargetIndex.A, PathEndMode.Touch)
                .WithProgressBarToilDelay(TargetIndex.A)
                .PlaySoundAtStart(SoundDefOf.Hacking_Started)
                .PlaySustainerOrSound(SoundDefOf.Hacking_InProgress)
                .WithEffect(EffecterDefOf.Hacking, TargetIndex.A); ;

            //This tells the game to run the registration process once the above wait is finished. I won't lie, at the time of writing, I still have no idea what delegate is
            yield return new Toil
            {
                initAction = delegate
                {
                    //gets hediff for later use
                    MJUWE_PortThingComp port = TargetThingA.TryGetComp<MJUWE_PortThingComp>();
                    //if statement just in case something breaks
                    if (pawn.health.hediffSet.TryGetHediff(MJUWE_DefOf.MJUWE_MindJackHediff, out Hediff hediff))
                    {
                        //registration
                        MJUWE_MindJack mindjack = (MJUWE_MindJack)hediff;
                        mindjack.registeredWeapon = TargetThingA;
                        mindjack.isRegistered = true;
                        port.ConnectToPort(pawn, mindjack);
                        CompQuality wepQuality = TargetThingA.TryGetComp<CompQuality>();

                        if (wepQuality.Quality > QualityCategory.Good)
                        {
                            //All unique weapons generated by the game have Art by default, so CompArt will already be set
                            //This method should not add Art to a weapon that was modded to attach a unique trait and has no Art already.
                            wepQuality.SetQuality(QualityCategory.Good, null);
                        }
                    }
                }

            };
        }
    }
}


