using MindJackMod;
using RimWorld;
using System;
using Verse;
using Verse.AI;

namespace MindJackUniqueWeaponBind
{
    public class MJUBW_RegisterToWeapon : FloatMenuOptionProvider
    {
        protected override bool Drafted => true;
        protected override bool Undrafted => true;
        protected override bool Multiselect => false;

        //Adding the context menu item to allow Binding
        protected override FloatMenuOption GetSingleOptionFor(Thing clickedThing, FloatMenuContext context)
        {
            Pawn currentPawn = context.FirstSelectedPawn;
            //This checks if the selected weapon has a Port and Pawn has a mind jack installed
            if (clickedThing.HasComp<MJUWE_PortThingComp>() && currentPawn.health.hediffSet.TryGetHediff(MJUWE_DefOf.MJUWE_MindJackHediff, out Hediff hediff))
                {
                //Sets the port and mind jack so we can modify them later
                //Adds context menu "Bind to (Weapon Name)"
                //TOADD: Context menues for: PAWN W/O Mind Jack, PAWN W/ Registered Mind Jack
                return FloatMenuUtility.DecoratePrioritizedTask(new FloatMenuOption("MJUWE_Bind".Translate(clickedThing.Label), () =>
                {

                    //This calls the job that bonds upon completion

                    Job job = JobMaker.MakeJob(MJUWE_DefOf.MJUWE_MindJackRegistration, new LocalTargetInfo(clickedThing));
                    context.FirstSelectedPawn.jobs.TryTakeOrderedJob(job, JobTag.Misc);
                    /* MJUWE_PortThingComp port = clickedThing.TryGetComp<MJUWE_PortThingComp>();
                    mindjack.registeredWeapon = clickedThing;
                    port.ConnectToPort(currentPawn, mindjack);
                    CompQuality wepQuality = clickedThing.TryGetComp<CompQuality>();

                    if (wepQuality.Quality > QualityCategory.Good)
                    {
                        //All unique weapons generated by the game have Art by default, so CompArt will already be set
                        //This method should not add Art to a weapon that was modded to attach a unique trait and has no Art already.
                        wepQuality.SetQuality(QualityCategory.Good, null);
                    }
                    //JUST FOR TESTING REMOVE LATER
                    Log.Message(mindjack.registeredWeapon.Label);
                    Log.Message("Bind Clicked");
                    Log.Message(port.registeredPawn.NameFullColored); */ 
                }), context.FirstSelectedPawn, clickedThing);
            }
            return null;
        }
    }
}
       