using MindJackUniqueWeaponBind;
using RimWorld;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Verse;
using Verse.AI;
using Verse.Sound;
using static UnityEngine.GridBrushBase;

namespace MindJackMod
{
    //This is the Job that takes place whenever a Pawn tries to register a weapon
    internal class MJUWE_RegisterJob : JobDriver
    {
        public int finish = 1080;
        public const int tickProgression = GenTicks.TicksPerRealSecond;
        public int currentTick = 0;
        public float Progression => currentTick / finish;

        //To be honest, I just took MakeNewToils() of the JobDiver_Hack and repurposed it.
        public override bool TryMakePreToilReservations(bool errorOnFailed)
        {
            return pawn.Reserve(TargetThingA, job, 1, -1, null, errorOnFailed);
        }
        protected override IEnumerable<Toil> MakeNewToils()
        {

            this.FailOnDespawnedNullOrForbidden(TargetIndex.A);
            yield return Toils_Goto.GotoThing(TargetIndex.A, PathEndMode.Touch);
            yield return Toils_General.WaitWith(TargetIndex.A, finish)
                .FailOnDestroyedNullOrForbidden(TargetIndex.A)
                .FailOnCannotTouch(TargetIndex.A, PathEndMode.Touch)
                .WithProgressBarToilDelay(TargetIndex.A)
                .PlaySoundAtStart(SoundDefOf.Hacking_Started)
                .PlaySustainerOrSound(SoundDefOf.Hacking_InProgress)
                .WithEffect(EffecterDefOf.Hacking, TargetIndex.A); ;
            yield return new Toil
            {
                initAction = delegate
                {
                    MJUWE_PortThingComp port = TargetThingA.TryGetComp<MJUWE_PortThingComp>();
                    Log.Message("Here");
                    if (pawn.health.hediffSet.TryGetHediff(MJUWE_DefOf.MJUWE_MindJackHediff, out Hediff hediff))
                    {
                        MJUWE_MindJack mindjack = (MJUWE_MindJack)hediff;
                        mindjack.registeredWeapon = TargetThingA;
                        port.ConnectToPort(pawn, mindjack);
                        CompQuality wepQuality = TargetThingA.TryGetComp<CompQuality>();

                        if (wepQuality.Quality > QualityCategory.Good)
                        {
                            //All unique weapons generated by the game have Art by default, so CompArt will already be set
                            //This method should not add Art to a weapon that was modded to attach a unique trait and has no Art already.
                            wepQuality.SetQuality(QualityCategory.Good, null);
                        }
                    }
                }

            };
        }
    }
}


